# Generated by Django 3.2.9 on 2021-12-01 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211201_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='bidders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='commenters', to=settings.AUTH_USER_MODEL),
        ),
    ]
