# Generated by Django 3.2.9 on 2021-12-01 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211201_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ManyToManyField(related_name='lister', to=settings.AUTH_USER_MODEL),
        ),
    ]
